
platform :ios, '9.0'
#use_frameworks!
project './player.xcodeproj'
target 'player' do
    
    #GCDWebServer 添加了favicon。
    pod 'GCDWebServer', '3.5.3'
    pod 'GCDWebServer/WebUploader', '3.5.3'
    pod 'GCDWebServer/WebDAV', ' 3.5.3'
    pod 'AFNetworking'
    pod 'SDWebImage'
    pod 'MobileVLCKit'
    pod 'RNCryptor-objc'
    pod 'TZImagePickerController'
    pod 'ZipArchive'
    pod 'UMCCommon'
    pod 'UMCAnalytics'
    pod 'UMCPush'
    pod 'UMCSecurityPlugins'
    pod 'UMCShare/UI'
    pod 'UMCShare/Social/WeChat'
    pod 'UMCShare/Social/QQ'
    pod 'UMCShare/Social/SMS'
    pod 'UMCShare/Social/Email'
    pod 'Google-Mobile-Ads-SDK'
    
end
